---
title: "Forest Sampling"
author: "Karin Wolken"
date: "2017-07-07"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{forestSampling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Forest Sampling Package   
  
The Forest Sampling is a package of functions that calculates workups for sampling designs commonly used in Forestry.
  
## General Information
  
All functions require data input. For most functions, this data must be a dataframe formatted in the generalized structure. Select functions can act on vectors ('summarize_simple_random' and 'summarize_systematic').  
In most cases, additional parameters are necessary. Defaults have been provided to help minimize this.  
  
Common parameters, detailed:  
* 'Attribute': assumes target attribute is called ‘attr’. Set 'attribute' to the column header used for the attribute of interest. Not required for vector input.  
* '___Tot': total number of the ___ unit in the sampling design. Commonly the total number of clusters or plots in the sampling frame.  
* 'desiredConfidence': Percent confidence level (two-sided). Default is set to '0.95'.  



